### ISSUE TITLE
training dataset

### ISSUE THREAD

**Issue by clelouch** [backseason/DFI#6]
Thansk for your great work! 
I find that the number of training images in saliency detection, edge detection and skeleton detection is different. Thus, I am curious about how to learn the three tasks simulataneously?

**Comment by backseason** [comment]
Let `N_s`, `N_e`, and `N_k` represent the number of training samples of the saliency, edge and skeleton datasets, respectively. 
During each iteration, we random sample an index `i` within the range of `[0, max([N_s, N_e, N_k]))`.
Then the samples of indexes `i % N_s`, `i % N_e`, and `i % N_k` are used to select the training samples for the saliency, edge, and skeleton tasks with respect to the corresponding datasets.
It's just a work-around for random sampling from datasets of different shapes.

**Comment by clelouch** [comment]
Many thanks for your kind reply!
